# Generated by Django 4.2.7 on 2023-12-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0002_alter_problem_source_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="source_type",
            field=models.CharField(
                choices=[("codeforces", "Codeforces"), ("atcoder", "AtCoder"), ("cses", "CSES")],
                default="codeforces",
                max_length=50,
            ),
        ),
    ]
