# Generated by Django 4.2.7 on 2023-12-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0003_alter_problem_source_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(fields=["url"], name="problems_pr_url_6b5bb6_idx"),
        ),
    ]
